### ISSUE TITLE
Can't get SearchQueryParser to work : $request->get('loadOptions') returns null

### ISSUE THREAD

**Issue by gnutix** [Elma/DevExpressBundle#16]
Hello folks,

I'm trying to use this bundle to display data in a `dxDataGrid` table using DevExtreme `20.1.6` (latest version). However, I can't find out how to pass the right properties to `SearchQueryParser::parse()` : the code samples in the README use `$request->get('loadOptions')`, but it returns `null` and fail on `json_decode()`.

Here's the two JS code I've found that I've tried (as none is provided with this bundle) :

Option 1 : https://gist.github.com/gnutix/5872b21f98993b1e01a37f199d927359 (inspired by https://github.com/DevExpress/DevExtreme-PHP-Data/blob/master/example/js/index.js )
Option 2 : https://gist.github.com/gnutix/03426bc4beda87a4126787373795b980 (inspired by https://js.devexpress.com/Documentation/Guide/Data_Binding/Specify_a_Data_Source/Custom_Data_Sources/#Load_Data/Server-Side_Data_Processing )

Both failed. Is `SearchQueryParser` compatible with the current version of DevExtreme ? Is there a specific trick to get it working I might have missed ?

Thanks for your help.

**Comment by mgiraud** [comment]
Hi,

Can you please check the content of your request, and check if the loadOptions field exists and is a valid JSON.

**Comment by gnutix** [comment]
Hello,

If I created this issue, it's because none of the code sample I've tried from the DevExtreme documentation produced a request containing `loadOptions` as a JSON. So I'm wondering if your bundle only works with a previous or other version of the library (as there's also DevExpress) ?

Could you please share with me some JavaScript code you use successfully with this bundle ?

**Comment by mgiraud** [comment]
Sorry, it's been a while since I have used this bundle. Here is an example of a custom datastore.
The loadOptions are bound to a 'loadOptions' param. Thanks for pointing this up, it's quite unclear

```js
var store = new DevExpress.data.CustomStore({
            load: function (loadOptions) {
                var d = $.Deferred();
                $.getJSON('/some/url, {'loadOptions': JSON.stringify(loadOptions)}).done(function (data) {
                    d.resolve(data.content, {
                        totalCount: data.total
                    });
                });
                return d.promise();
            }
        });

```

**Comment by gnutix** [comment]
Thank you very much! Your example helped me get a working DataGrid. :)

I guess it would be worth upgrading the README. I might open a PR for that if I get some time (there's more things in there I'd like to write, like the different supported features and how to enable them).
